/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('User', [{
      id: 1,
      firstName: 'Admin1',
      lastName: '',
      email: 'admin1@gmail.com',
      password: 'imadmin1',
      course: null,
      attendance: 0,
      enrolled: false,
      isAdmin: true,
      isTeacher: false,
    },
    {
      id: 2,
      firstName: 'Admin2',
      lastName: '',
      email: 'admin2@gmail.com',
      password: 'imadmin2',
      course: null,
      attendance: 0,
      enrolled: false,
      isAdmin: true,
      isTeacher: false,
    },
    {
      id: 3,
      firstName: 'Teacher1',
      lastName: 'One',
      email: 'teacher1@gmail.com',
      password: 'imteacher1',
      course: null,
      attendance: 0,
      enrolled: false,
      isAdmin: false,
      isTeacher: true,
    },
    {
      id: 4,
      firstName: 'Teacher2',
      lastName: 'Two',
      email: 'teacher2@gmail.com',
      password: 'imteacher2',
      course: null,
      attendance: 0,
      enrolled: false,
      isAdmin: false,
      isTeacher: true,
    },
    {
      id: 5,
      firstName: 'student1',
      lastName: 'Onestudent',
      email: 'student1@gmail.com',
      password: 'imtstudent1',
      course: null,
      attendance: 0,
      enrolled: false,
      isAdmin: false,
      isTeacher: false,
    },
    {
      id: 6,
      firstName: 'student2',
      lastName: 'Twostudent',
      email: 'student2@gmail.com',
      password: 'imtstudent2',
      course: null,
      attendance: 0,
      enrolled: false,
      isAdmin: false,
      isTeacher: false,
    }], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('User', null, {});
  },
};
