version: '3.8'

services:
  db-lounge-rent:
    image: mysql:5.7
    container_name: db-lounge-rent
    environment:
      MYSQL_DATABASE: academy
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d




