version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: club_de_horas
    ports:
      - "3307:3306"
    volumes:
      - ./bd:/docker-entrypoint-initdb.d
